### ISSUE TITLE
[FEAT] inference.py 구축

### ISSUE THREAD

**Issue by dangnidang** [aaiss0927/SINSA_Python#9]
## Background
- inference.py를 구축하였습니다.

## Todo
- [ ] Todo 1 : 모델 생성
- [ ] Todo 2 : 모델 학습
- [ ] Todo 3: 모델 구축

## See also
- #
